global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'edutech-platform'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cursos-api'
    static_configs:
      - targets: ['app-cursos:3001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'notificaciones'
    static_configs:
      - targets: ['app-notificaciones:3002']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s
